Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server-2019-standard"
  config.vm.communicator = "winrm"

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.network "forwarded_port", guest: 3389, host: 3390, auto_correct: true
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.ps1"
end
